### ISSUE TITLE
Does Aura support time stretching?

### ISSUE THREAD

**Issue by http-80** [MoritzBrueckner/aura#6]
Hi!

Is it possible to change the audio speed using aura (specifically without changing pitch)?

With kind regards,

**Comment by MoritzBrueckner** [comment]
Hi, at the moment there is no support for time stretching in Aura out of the box. You can of course write your own DSP effect like you wrote on the Kha Discord so it's still technically possible. You mentioned that you didn't succeed doing this, was this because of Aura itself (e.g. you didn't understand how to adapt your solution to Aura) or because of the algorithm/maths itself? Feel free to ask your questions here (or in a [discussion](https://github.com/MoritzBrueckner/aura/discussions/categories/q-a)), I'm happy to help (if I'm able to do so).

What's your use case if I may ask? There are various time stretching algorithms which not only have a different quality and performance but also work differently for different kinds of sounds.

I'm not an expert on DSP (quite the opposite actually), but [granular synthesis](https://blog.demofox.org/2018/03/05/granular-audio-synthesis/) sounds like a simple algorithm that still gives reasonable results in many cases. Maybe this is a good starting point?

**Comment by http-80** [comment]
Thank you for your quick response!

I'd like and attempt to write a rhythm game using haxe/kha, and I'd like to add modifiers to increase speed, which I'd like to do without affecting pitch.
I'm pretty new to Aura, which is one of the current factors as to why I struggle a bit. But mainly finding resources/understanding the math behind is currently my biggest problem.

With kind regards,
http80

**Comment by MoritzBrueckner** [comment]
If you only want to increase speed as you wrote it's probably rather straightforward to implement, but if you also want to decrease the spead I think you might need to two different approaches for each direction if you want to implement this as a DSP effect. The reason for this is that in each "audio frame", Aura requests a certain amount of samples from each playing channel (currently that amount is hard-coded to [512](https://github.com/MoritzBrueckner/aura/blob/0d2567c812a1ddfc77e0e554faad4e841a690b7b/Sources/aura/Aura.hx#L47-L51) but this might change in the future) and only afterwards executes all DSP effects on that channel. This means that the way in which Aura works currently is not working well if DSP effects need to change the playback speed.

But there are workarounds:
- If you want to speed up the playback (= you want to fit more samples into the same amount of time), you can probably call the channel's [`nextSamples()`](https://github.com/MoritzBrueckner/aura/blob/0d2567c812a1ddfc77e0e554faad4e841a690b7b/Sources/aura/channels/BaseChannel.hx#L167) function with the extra samples you need _within_ the effect's [`process`](https://github.com/MoritzBrueckner/aura/blob/0d2567c812a1ddfc77e0e554faad4e841a690b7b/Sources/aura/dsp/DSP.hx#L14) function. This will also advance the read pointer in the audio source by the amount of samples you specified, so the next call of `process()` will receive parts of the audio signal starting from the correct position. For example, if you want to process 1024 samples for each audio frame with 512 samples, you would first process the 512 samples Aura passes to `process()` and then call process again with a new batch of 512 samples from another `nextSamples()` call. In the next frame, Aura already advanced the read pointer by 1024 samples then.
- Slowing down the playback is more tricky in theory, as `process()` gets more samples than you actually need. You can't just store them temporarily in a buffer, because the buffer would continuously need to grow as the playback lags behind the audio source further and further. However, I think that there is a really simple workaround for this: You can change the channel's [pitch](https://github.com/MoritzBrueckner/aura/blob/0d2567c812a1ddfc77e0e554faad4e841a690b7b/Sources/aura/channels/UncompBufferResamplingChannel.hx#L21) value so that you get a slower sound (which also has lower pitch) which you then resample (there's a [helper utility](https://github.com/MoritzBrueckner/aura/blob/master/Sources/aura/utils/Resampler.hx) for this) to essentially undo the pitch (with some minor quality losses, I guess). This way Aura only advances a smaller amount of source samples per frame that it would otherwise.
- If you need more flexibility, you could also implement a custom audio channel where you can directly control the playback speed. The downside of this is that you need to dig deeper into Aura internals and you also might need to expose some of them to the code outside of the library.

**Comment by http-80** [comment]
Hi!

I managed to implement the slowdown, however I am still confused on the speedup though.
Do I just make the channel one of the arguments, then make nextSamples a public function, and call it every process tick? (to advance the read pointer at twice the rate?)

Thanks in advance!

**Comment by MoritzBrueckner** [comment]
Hi, sorry for my late answer, I fell ill a few days ago and so far didn't have a clear head to actually answer. Depending on how fast I get well again my next answers might also take a few days.

> Do I just make the channel one of the arguments

Yes, DSP effects currently can't access the channel they belong to so you need to pass the channel as a constructor parameter, for example.

Implementing a channel attribute for all DSP effects would be easy of course, but I'm undecided about whether I want to add it since DSP effects should be mostly independent of their channels. If effects were able to control their channels this would be kind of an inversion of responsibility.

>  then make nextSamples a public function

If you don't want to modify Aura you can also use `@:privateAccess channel.nextSamples(buffer, sampleRate)` instead of making that function public. It's of course somehat hacky, but after all, the entire solution for this DSP effect is somewhat hacky :)

> and call it every process tick? (to advance the read pointer at twice the rate?)

What I had in mind is something like this (I now realize that I didn't think this quite through initially, so it's even more hacky and ugly):
```haxe
// In your DSP effect:

function process(buffer: AudioBuffer) {
	processPrivate(buffer);

	final previousChannelLength = buffer.channelLength;
	buffer.channelLength = /* Whatever amount of additional samples you need, must not be larger than the previous amount */;

	@:privateAccess channel.nextSamples(buffer, Aura.sampleRate); // Request a second batch of samples
	processPrivate(buffer);

	// If you need more than twice the amount of samples per frame
	// because you want to more than double the playback speed,
	// you either need to allocate a larger buffer for calling nextSamples()
	// or you need to call nextSamples() more often until you processed all samples you need.

	buffer.channelLength = previousChannelLength; // Restore length for this audio buffer so that subsequent effects and audio frames aren't cut off
}

function processPrivate(buffer: AudioBuffer) {
	// Your actual time-stretching code
}
```

What I didn't show in the above example is that you likely need to allocate a second audio buffer because the call to `nextSamples()` would override the results from the first `processPrivate()` call. Depending on how you implement this, you might not need to temporarily change `buffer.channelLength`. If you don't want to call your `process()` function manually with an arbitrary amount of samples, you can allocate the second buffer with a fixed size in the constructor of your DSP effect, the buffer channel length used by Aura can be found [here](https://github.com/MoritzBrueckner/aura/blob/0d2567c812a1ddfc77e0e554faad4e841a690b7b/Sources/aura/Aura.hx#L49) in case you need it. If you want the DSP effect to be more dynamic (i.e. you want to call `process()` manually somewhere else and the second buffer shouldn't have a fixed size), you should rather use Aura's `BufferCache` and request a cached buffer in the process function, similar to how it's done [here](https://github.com/MoritzBrueckner/aura/blob/0d2567c812a1ddfc77e0e554faad4e841a690b7b/Sources/aura/threading/BufferCache.hx#L58-L66) or [with `p_samplesBuffer`](https://github.com/MoritzBrueckner/aura/blob/0d2567c812a1ddfc77e0e554faad4e841a690b7b/Sources/aura/Aura.hx#L50) in Aura.hx.

This got a bit more complicated than I initially anticipated, if you have any ideas on how to improve Aura please let me know :)

**Comment by MoritzBrueckner** [comment]
I guess something like this would be a better solution than what I proposed above (untested and only works for speedup, not for slowdown):

```haxe
class TimeStretcher extends DSP {
	var channel: BaseChannel;
	var speedFactor: Float;
	var p_additionalBuffer = new Pointer<AudioBuffer>(null);

	public function new(channel: BaseChannel, speedFactor: Float) {
		this.channel = channel;
		setSpeedFactor(speedFactor);
	}

	public function setSpeedFactor(speedFactor: Float) {
		final numAdditionalSamples = Aura.BLOCK_CHANNEL_SIZE * speedFactor - Aura.BLOCK_CHANNEL_SIZE;
	
		if (!BufferCache.getBuffer(TAudioBuffer, p_additionalBuffer, Aura.NUM_OUTPUT_CHANNELS, numAdditionalSamples)) {
			trace("Could not allocate buffer for TimeStretcher DSP");
			return;
		}

		this.speedFactor = speedFactor;
	}

	function process(buffer: AudioBuffer) {
		final additionalBuffer = p_additionalBuffer.get();
	
		// Buffer allocation failed
		if (additionalBuffer == null) {
			return;
		}

		final samplesWritten = processPrivate(buffer, buffer, 0);

		@:privateAccess channel.nextSamples(additionalBuffer, Aura.sampleRate);

		processPrivate(additionalBuffer, buffer, samplesWritten);
	}

	function processPrivate(inputBuffer: AudioBuffer, outputBuffer: AudioBuffer, outputOffset: Int): Int {
		// Your time-stretching code. Takes the samples from inputBuffer and
		// copies them into output buffer, starting at the per-channel sample offset outputOffset.
		// This function returns the amount of samples written
	}
}
```

However, it does not work if you want to call `process()` manually with custom buffer sizes as it expects the size of the buffer passed to `process()` to be equal to `Aura.BLOCK_CHANNEL_SIZE`.
